%% Collect experiment image metadata
%
% This script collects the metadata from the experiment image data files and
% writes it to a CSV file. Metadata is only read from the file headers, the
% image data itself is not read.
%
% The metadata gives an overview of the experiment data and can help identify
% corrupt image files.
%
% The script requires the BioFormats toolbox and the OMEImageReaderLazy class to
% be accessible on the MATLAB path. They can be found here:
% - BioFormats toolbox: www.openmicroscopy.org/bio-formats/
% - OMEImageReaderLazy: <to be done>
%
% If the MATLAB path can't be adjusted in the MATLAB client software (e.g. on a
% compute cluster), add the respective paths during runtime.

% addpath(fullfile(".", "bfmatlab"));
% addpath(fullfile(".", "OMEImageReaderLazy"));

%% Process parameter section

% image data source directories
sourceDirectories = [ ...
	fullfile("..", "Exp1_Round1_complete", "Control_06h"), ...
	fullfile("..", "Exp1_Round1_complete", "Control_12h"), ...
	fullfile("..", "Exp1_Round1_complete", "Control_24h"), ...
	fullfile("..", "Exp1_Round1_complete", "RHB_06h"), ...
	fullfile("..", "Exp1_Round1_complete", "RHB_12h"), ...
	fullfile("..", "Exp1_Round1_complete", "RHB_24h"), ...
	fullfile("..", "Exp1_Round1_complete", "RHB_48h"), ...
	fullfile("..", "Exp1_Round1_complete", "RHB_72h"), ...
	fullfile("..", "Exp1_Round2_complete", "Control_06h"), ...
	fullfile("..", "Exp1_Round2_complete", "Control_12h"), ...
	fullfile("..", "Exp1_Round2_complete", "Control_24h"), ...
	fullfile("..", "Exp1_Round2_complete", "RHB_06h"), ...
	fullfile("..", "Exp1_Round2_complete", "RHB_12h"), ...
	fullfile("..", "Exp1_Round2_complete", "RHB_24h"), ...
	fullfile("..", "Exp1_Round2_complete", "RHB_48h"), ...
	fullfile("..", "Exp1_Round2_complete", "RHB_72h"), ...
	fullfile("..", "Exp2_Round1_complete", "Control_06h"), ...
	fullfile("..", "Exp2_Round1_complete", "Control_12h"), ...
	fullfile("..", "Exp2_Round1_complete", "Control_24h"), ...
	fullfile("..", "Exp2_Round1_complete", "RHB_06h"), ...
	fullfile("..", "Exp2_Round1_complete", "RHB_12h"), ...
	fullfile("..", "Exp2_Round1_complete", "RHB_24h"), ...
	fullfile("..", "Exp2_Round1_complete", "RHB_48h"), ...
	fullfile("..", "Exp2_Round1_complete", "RHB_72h"), ...
	fullfile("..", "Exp2_Round2_complete", "Control_06h"), ...
	fullfile("..", "Exp2_Round2_complete", "Control_12h"), ...
	fullfile("..", "Exp2_Round2_complete", "Control_24h"), ...
	fullfile("..", "Exp2_Round2_complete", "RHB_06h"), ...
	fullfile("..", "Exp2_Round2_complete", "RHB_12h"), ...
	fullfile("..", "Exp2_Round2_complete", "RHB_24h"), ...
	fullfile("..", "Exp2_Round2_complete", "RHB_48h"), ...
	fullfile("..", "Exp2_Round2_complete", "RHB_72h"), ...
	];

% condition labels (number must match source directories)
condLabels = [ ...
	"Experiment 1, Round 1, Control 06 h", ...
	"Experiment 1, Round 1, Control 12 h", ...
	"Experiment 1, Round 1, Control 24 h", ...
    "Experiment 1, Round 1, RHB 06 h", ...
    "Experiment 1, Round 1, RHB 12 h", ...
    "Experiment 1, Round 1, RHB 24 h", ...
    "Experiment 1, Round 1, RHB 48 h", ...
    "Experiment 1, Round 1, RHB 72 h", ...
	"Experiment 1, Round 2, Control 06 h", ...
	"Experiment 1, Round 2, Control 12 h", ...
	"Experiment 1, Round 2, Control 24 h", ...
    "Experiment 1, Round 2, RHB 06 h", ...
    "Experiment 1, Round 2, RHB 12 h", ...
    "Experiment 1, Round 2, RHB 24 h", ...
    "Experiment 1, Round 2, RHB 48 h", ...
    "Experiment 1, Round 2, RHB 72 h", ...
	"Experiment 2, Round 1, Control 06 h", ...
	"Experiment 2, Round 1, Control 12 h", ...
	"Experiment 2, Round 1, Control 24 h", ...
    "Experiment 2, Round 1, RHB 06 h", ...
    "Experiment 2, Round 1, RHB 12 h", ...
    "Experiment 2, Round 1, RHB 24 h", ...
    "Experiment 2, Round 1, RHB 48 h", ...
    "Experiment 2, Round 1, RHB 72 h", ...
	"Experiment 2, Round 2, Control 06 h", ...
	"Experiment 2, Round 2, Control 12 h", ...
	"Experiment 2, Round 2, Control 24 h", ...
    "Experiment 2, Round 2, RHB 06 h", ...
    "Experiment 2, Round 2, RHB 12 h", ...
    "Experiment 2, Round 2, RHB 24 h", ...
    "Experiment 2, Round 2, RHB 48 h", ...
    "Experiment 2, Round 2, RHB 72 h", ...
	];

% condition indexing (number must match source directories)
condInds = (1:numel(condLabels))';

% metadata output file
metadataFile = fullfile(".", "metadata_temp.csv");

%% Main script section

% metadata result table
metadataTable = table(Size=[0,13], ...
    VariableNames=["FileName","CondName","CondInd","SeriesTotal","SeriesInd","SizeC","SizeX","SizeY","SizeZ","SizeT","VoxelSizeX","VoxelSizeY","VoxelSizeZ"], ...
    VariableTypes=["string","string","int32","int32","int32","int32","int32","int32","int32","int32","double","double","double"]);

numDirs = numel(sourceDirectories);

for cc = 1:numDirs

	thisDir = sourceDirectories(cc);

	fprintf("Directory %d of %d (%s)\n", cc, numDirs, thisDir)

	listing = rdir(char(fullfile(thisDir, "*.nd2")), '~contains(name,''._'')');

	numFiles = numel(listing);

    condName = condLabels(cc);
	condInd = condInds(cc);

	for ff = 1:numFiles

		combined_filepath = fullfile(listing(ff).name);

		fprintf("File %d of %d (%s)\n", ff, numFiles, combined_filepath)

        reader = OMEImageReaderLazy(combined_filepath);
        numSeries = reader.getNumSeries(); % Fast, uses metadata only

        for ss = 1:numSeries
            
            fprintf("Series %d of %d\n", ss, numSeries)

            numChannels = reader.getNumChannels(ss);
            imgSize = reader.getStackSizeXYZ(ss);
            numTime = reader.getSizeT(ss);
		 	voxelSize = [reader.getPixelSizeXY(ss), reader.getZStepSize(ss)];

            metadataTable(end + 1, :) = {string(combined_filepath), string(condName), condInd, numSeries, ss, numChannels, imgSize(1), imgSize(2), imgSize(3), numTime, voxelSize(1), voxelSize(2), voxelSize(3)};

        end
        reader.close(); % Always close reader after use!

	end

end

writetable(metadataTable, metadataFile);
